### ISSUE TITLE
please beautify my portfolio with grids

### ISSUE THREAD

**Issue by charan1922** [charan1922/myportfolio#15]
**My URL:** https://charan1922.github.io/myPortfolio/#Portfolio_redirect

How to create grids to include projects in my portfolio section.
something like in below picture
![im](https://user-images.githubusercontent.com/23609292/31853638-5b5a383c-b6a9-11e7-8da4-d14fb4008dce.jpg)

I want to include this project (https://codesandbox.io/s/j384k3zm93) in one of the grids such that when I click it , then it should redirect to that URL

**Comment by nick-xie** [comment]
I think it looks great so far! Is there anything in particular that you would like specific help with?

**Comment by omergulen** [comment]
I can't go to your webiste but used grid system in your project and you can pull it from there.
https://codesandbox.io/s/oxjqxnqkq5

**Comment by DigitalDesignerOnline** [comment]
can this be considered a open source project when it has elements which were purchased from codecanyon? After all Hacktoberfest is for assisting others in open source projects and creating awareness not to get free services.
