### ISSUE TITLE
Please add buttons to navigate to next section in portfolio

### ISSUE THREAD

**Issue by charan1922** [charan1922/myportfolio#21]
In my portfolio section, I want to add NEXT and PREV buttons to Navigate. 
![pp](https://user-images.githubusercontent.com/23609292/32172456-a97ff476-bda1-11e7-8e96-c503c6215187.jpg)

I want only 4 grids in one section.

Please help me add buttons 
![button](https://user-images.githubusercontent.com/23609292/32172488-cf95ad36-bda1-11e7-8179-64fd975767ad.jpg)

**Comment by AshBardhan** [comment]
Is NEXT and PREV functionality working? Are you expecting that feature to be made as well along with the UI?

**Comment by AshBardhan** [comment]
`I want only 4 grids in one section.`
You mean 4 columns in one row?

**Comment by DigitalDesignerOnline** [comment]
can this be considered a open source project when it has elements which were purchased from codecanyon? After all Hacktoberfest is for assisting others in open source projects and creating awareness not to get free services.

there is even the themeforest link in the css file.....

**Comment by charan1922** [comment]
I forked it from another profile(for free) I don't know what is canyon and themeforest. For me it is open source.

**Comment by DigitalDesignerOnline** [comment]
no it is copyrighted materials, and if you forked it from someone else then that would show in your repo though it does not. your entire design is based off of a copyrighted product sold on the envato marketplace it is right there is hte css stylesheet. no worries.

* Template Name: Unique - Responsive vCard Template
* Author: lmpixels
* Author URL: http://themeforest.net/user/lmpixels

What you are doing can get yourself and many others in a lot of trouble for copyright infringement.....
