### ISSUE TITLE
The Portfolio option  is not redirecting to the specified link. Please fix.

### ISSUE THREAD

**Issue by charan1922** [charan1922/myPortfolio#4]
![pic](https://user-images.githubusercontent.com/23609292/31815979-0befdeda-b5ac-11e7-8eb0-567fc4395752.png)

In above pic when  I click portfolio option, It is not redirecting to the specific path that has linked to it. Please fix.

**This is my portfolio URL** : https://www.freecodecamp.org/charan1922

**Comment by imcgeek** [comment]
Requested a pull request after changes in your sample code.
