### ISSUE TITLE
Problem with the favicon.

### ISSUE THREAD

**Issue by charan1922** [charan1922/myPortfolio#9]
I want this
![images](https://user-images.githubusercontent.com/23609292/31834789-ddcd1720-b5ec-11e7-8e6d-a11694d9ed45.jpg)
as favicon. Please Help me

It is showing as 
![wrong](https://user-images.githubusercontent.com/23609292/31834987-86bb5676-b5ed-11e7-8008-2f0db623485a.png)

in
![picfull](https://user-images.githubusercontent.com/23609292/31835138-10cdc434-b5ee-11e7-85ee-5ded595b1e12.png)

**Comment by kylejohnston** [comment]
I can help with this
